### ISSUE TITLE
Will you make weight files public in the future？

### ISSUE THREAD

**Issue by zhanghao5201** [ZiyiZhang27/Dite-HRNet#4]

**Comment by ZiyiZhang27** [comment]
Sorry for the late reply!  All checkpoint files here: https://drive.google.com/drive/folders/1_unL2XMll5vL1_zstnm3EC9BVFr_jrsf?usp=sharing. In order to match the module names in the paper, we have renamed some classes in the code at a later stage, so a small part of the model file may not be available, we will retrain this part of the model if we have time next.
